apiVersion: batch/v1
kind: Job
metadata:
  name: sqlite-restore-specific  # Nom fixe, ou ajoute un timestamp si tu veux
  namespace: pra
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: restore
        image: pra/flask-sqlite:1.2
        command: ["/bin/sh"]
        args:
        - -c
        - |
          echo "Restauration depuis \$BACKUP_FILE"
          cp /backup/\$BACKUP_FILE /data/app.db
          echo "✅ Restauration terminée"
        env:
        - name: BACKUP_FILE
          value: "app-1772098381.db"  # ← CHANGE ICI le nom du backup
        volumeMounts:
        - name: data
          mountPath: /data
        - name: backup
          mountPath: /backup
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: pra-data
      - name: backup
        persistentVolumeClaim:
          claimName: pra-backup
